//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEurope
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Operation
    {
        public int OperationID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string OperationType { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_Property Tbl_Property { get; set; }
    }
}
