//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEurope
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Property()
        {
            this.Tbl_Operation = new HashSet<Tbl_Operation>();
        }
    
        public int PropertyID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> RoomNumbers { get; set; }
        public Nullable<double> PropertyArea { get; set; }
        public Nullable<double> RentPrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsRepaired { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Operation> Tbl_Operation { get; set; }
    }
}
