//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEurope
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Phone { get; set; }
    }
}
